import { DealType, Listing, PropertyType, Requirement, RequirementUrgency } from "./deal-types";

export const propertyTypeOptions: PropertyType[] = [
  "apartment",
  "villa",
  "townhouse",
  "penthouse",
  "office",
  "retail",
  "warehouse",
  "land",
];

export const dealTypeOptions: DealType[] = ["off_plan", "secondary", "distressed", "urgent_sale"];
export const urgencyOptions: RequirementUrgency[] = ["hot", "active", "planning"];

export const specialityOptions = [
  "Secondary Market",
  "Off-Plan",
  "Luxury",
  "Investment",
  "Mixed",
];

export const mockListings: Listing[] = [
  {
    id: "mock-listing-1",
    title: "Palm Jumeirah 4BR Signature Villa",
    property_type: "villa",
    deal_type: "secondary",
    bedrooms: 4,
    size_sqft: 5200,
    area_id: "mock-area-1",
    developer: "Nakheel",
    price: 23500000,
    payment_plan: "Cash or 40/60 structured close",
    handover_date: null,
    yield_percent: 6.5,
    property_video_url: null,
    notes: null,
    description: "Vacant-on-transfer waterfront villa with motivated seller and clean title.",
    status: "approved",
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "mock-broker-1",
    agency_id: "mock-agency-1",
    renewal_due_at: new Date().toISOString(),
    approved_at: new Date().toISOString(),
    credits_used: 1,
    area: { id: "mock-area-1", name: "Palm Jumeirah", city: "Dubai", slug: "palm-jumeirah" },
    commission_terms: { listing_id: "mock-listing-1", co_broke_percent: 2, payment_terms: "On transfer", notes: "Direct" },
    listing_images: [
      {
        id: "img-1",
        listing_id: "mock-listing-1",
        file_name: "cover.jpg",
        storage_path: "mock/cover.jpg",
        public_url: "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_cover: true,
      },
    ],
  },
  {
    id: "mock-listing-2",
    title: "Business Bay 2BR Investor Unit",
    property_type: "apartment",
    deal_type: "off_plan",
    bedrooms: 2,
    size_sqft: 1350,
    area_id: "mock-area-2",
    developer: "Select Group",
    price: 2850000,
    payment_plan: "Post-handover available",
    handover_date: "2026-08-30",
    yield_percent: 7.8,
    property_video_url: null,
    notes: null,
    description: "High-floor canal-facing unit with short close window and off-market pricing.",
    status: "approved",
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "mock-broker-2",
    agency_id: "mock-agency-2",
    renewal_due_at: new Date().toISOString(),
    approved_at: new Date().toISOString(),
    credits_used: 1,
    area: { id: "mock-area-2", name: "Business Bay", city: "Dubai", slug: "business-bay" },
    commission_terms: { listing_id: "mock-listing-2", co_broke_percent: 1.5, payment_terms: "On SPA", notes: "Qualified buyers only" },
    listing_images: [
      {
        id: "img-2",
        listing_id: "mock-listing-2",
        file_name: "cover.jpg",
        storage_path: "mock/cover-2.jpg",
        public_url: "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_cover: true,
      },
    ],
  },
  {
    id: "mock-listing-3",
    title: "JVC Premium Townhouse Block Deal",
    property_type: "townhouse",
    deal_type: "distressed",
    bedrooms: 3,
    size_sqft: 2800,
    area_id: "mock-area-3",
    developer: "Danube",
    price: 4100000,
    payment_plan: "Cash buyer preferred",
    handover_date: null,
    yield_percent: 8.2,
    property_video_url: null,
    notes: null,
    description: "Cluster release from a landlord exiting portfolio. Strong rental yield.",
    status: "approved",
    is_visible: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    created_by: "mock-broker-3",
    agency_id: "mock-agency-3",
    renewal_due_at: new Date().toISOString(),
    approved_at: new Date().toISOString(),
    credits_used: 1,
    area: { id: "mock-area-3", name: "JVC", city: "Dubai", slug: "jvc" },
    commission_terms: { listing_id: "mock-listing-3", co_broke_percent: 2.5, payment_terms: "On transfer", notes: "Portfolio deal" },
    listing_images: [
      {
        id: "img-3",
        listing_id: "mock-listing-3",
        file_name: "cover.jpg",
        storage_path: "mock/cover-3.jpg",
        public_url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
        sort_order: 0,
        is_cover: true,
      },
    ],
  },
];

export const mockRequirements: Requirement[] = [
  {
    id: "mock-req-1",
    title: "Family ready villa under AED 13M",
    deal_type: "secondary",
    property_type: "villa",
    bedrooms: "4BR",
    broker_id: "mock-broker-profile-1",
    area_id: "mock-area-4",
    budget_min: 10000000,
    budget_max: 13000000,
    urgency: "hot",
    description: "Cash-ready GCC family searching for a move-in-ready villa with a quick close.",
    notes: "Cash-ready GCC family, close within 21 days.",
    timeline: "Close within 21 days",
    is_active: true,
    deactivated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    posted_by: "mock-broker-1",
    area: "Dubai Hills",
  },
  {
    id: "mock-req-2",
    title: "Yield-led office search in DIFC",
    deal_type: "distressed",
    property_type: "office",
    bedrooms: null,
    broker_id: "mock-broker-profile-2",
    area_id: "mock-area-5",
    budget_min: 5000000,
    budget_max: 9000000,
    urgency: "active",
    description: "Investor wants a tenanted office unit in DIFC with strong net yield.",
    notes: "Investor wants existing tenancy and 7%+ net yield.",
    timeline: "Immediate review",
    is_active: true,
    deactivated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    posted_by: "mock-broker-2",
    area: "DIFC",
  },
  {
    id: "mock-req-3",
    title: "Urgent 2BR buyer brief for relocation client",
    deal_type: "urgent_sale",
    property_type: "apartment",
    bedrooms: "2BR",
    broker_id: "mock-broker-profile-3",
    area_id: "mock-area-2",
    budget_min: 150000,
    budget_max: 190000,
    urgency: "planning",
    description: "Relocation client wants a furnished 2BR with a fast move-in window.",
    notes: "Move-in target in 45 days, furnished preferred.",
    timeline: "Within 45 days",
    is_active: true,
    deactivated_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    posted_by: "mock-broker-3",
    area: "Business Bay",
  },
];

